export const SAMPLE_CHAT_USER_ID = 'BQQywmO6uIbp3jC8Fet3iD9cG063';
export const SAMPLE_CHAT_USER_PERSONALITY = 'kyle';
export const GET_CHAT_HISTORY_QUERY_KEY = 'GET_USER_CHAT_HISTORY_QUERY_KEY';
export const GET_USER_PERSONALITIES_LIST_KEY = 'GET_USER_PERSONALITIES_LIST_KEY';
